arrowParens: "avoid"
bracketSpacing: true
endOfLine: "auto"
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: ["*.sol"]
    options:
      compiler: "0.8.15"
      tabWidth: 4
