name: Add issue to task board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to task board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/vacp2p/projects/10
          github-token: ${{ secrets.ADD_TO_VAC_BOARD_PAT }}
